name: ${project.name}
version: ${project.version} (Build ${git.commit.id.abbrev}, ${git.commit.time})
description: ${project.description}
author: jmsgvn
main: ${project.groupId}.${project.artifactId}
depend: [ProtocolLib]
commands:
  ping:
    description: Get the ping of a player
    usage: /<command>
  toggletab:
    description: Toggle the tab
    usage: /<command>
  toggleboard:
    description: Toggle the scoreboard
    usage: /<command>
    aliases:
      - togglescoreboard

